import type { ThemeConfig } from 'antd'

export const appTheme: ThemeConfig = {
  token: {
    colorPrimary: '#4A7C6F',
    colorInfo: '#4A7C6F',
    colorSuccess: '#4A7C6F',
    colorWarning: '#E0A63C',
    colorError: '#D96A4A',
    colorLink: '#3E6B5E',
    colorLinkHover: '#4A7C6F',
    colorLinkActive: '#2E5347',
    colorBgLayout: '#F5F1E6',
    colorBgContainer: '#FBF8F0',
    colorBgElevated: '#FCFAF3',
    colorText: '#2E3A34',
    colorTextHeading: '#22302A',
    colorTextSecondary: '#6B7B72',
    colorBorder: '#E4DCC9',
    colorBorderSecondary: '#EBE4D3',
    colorFillSecondary: 'rgba(74,124,111,0.08)',
    colorFillTertiary: 'rgba(74,124,111,0.05)',
    colorFillQuaternary: 'rgba(74,124,111,0.03)',
    controlItemBgActive: '#E4EDE7',
    controlItemBgHover: '#EEF3EF',
    borderRadius: 12,
    borderRadiusLG: 16,
    borderRadiusSM: 8,
    fontFamily: "'Noto Sans SC', -apple-system, sans-serif",
    fontSize: 15,
    boxShadow: 'none',
    boxShadowSecondary: 'none',
    boxShadowTertiary: 'none',
    lineWidth: 1,
    lineType: 'solid',
    controlHeight: 40,
  },
  components: {
    Button: {
      primaryShadow: 'none',
      defaultShadow: 'none',
      dangerShadow: 'none',
    },
    Card: {
      paddingLG: 32,
    },
    Menu: {
      itemBg: '#FBF8F0',
      subMenuItemBg: '#FBF8F0',
      itemSelectedBg: '#E4EDE7',
      itemSelectedColor: '#3E6B5E',
      itemHoverBg: '#EEF3EF',
    },
    Layout: {
      headerBg: '#FBF8F0',
      siderBg: '#FBF8F0',
      bodyBg: '#F5F1E6',
    },
    Table: {
      headerBg: '#F1EADB',
      headerColor: '#2E3A34',
      headerSortActiveBg: '#ECE4D1',
      headerSortHoverBg: '#EFE7D6',
      rowHoverBg: '#F3EEE1',
      borderColor: '#EBE4D3',
    },
    Slider: {
      railBg: '#E4DCC9',
      railHoverBg: '#DAD0B9',
      trackBg: '#4A7C6F',
      trackHoverBg: '#3E6B5E',
      handleColor: '#4A7C6F',
      handleActiveColor: '#3E6B5E',
      dotActiveBorderColor: '#4A7C6F',
    },
    Select: {
      optionSelectedBg: '#E4EDE7',
      optionSelectedColor: '#3E6B5E',
    },
    Input: {
      hoverBorderColor: '#7FA99B',
      activeBorderColor: '#4A7C6F',
    },
    Tag: {
      defaultBg: '#EFE8DA',
      defaultColor: '#6B7B72',
    },
    Modal: {
      boxShadow: 'none',
      contentBg: '#FCFAF3',
    },
    Popover: {
      boxShadow: 'none',
    },
    Dropdown: {
      boxShadow: 'none',
    },
  },
}
